# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20241217.1"
  config.vm.box_check_update = false

  # Server node - K3s controller
  config.vm.define "akheiredS" do |server|
    server.vm.hostname = "akheiredS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "akheiredS"]
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # Worker node - K3s agent
  config.vm.define "akheiredSW" do |worker|
    worker.vm.hostname = "akheiredSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "akheiredSW"]
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end